### ISSUE TITLE
Creation du launcher_profiles.json pour NoLogin

### ISSUE THREAD

**Issue by BrokenFire** [Litarvan/OpenAuth#1]
Salut!

En voulant utiliser NoLogin, celui ci plante parce-que le fichier launcher_profiles.json n'est pas générer, alors je voudrais savoir comment le généré.

Merci d'avance ;)

**Comment by Litarvan** [comment]
Ce n'est pas ma librairie, il faut aller sur le repo en quesiton : https://github.com/Lifok/NoLogin
