### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by Florianpal1** [Litarvan/OpenAuth#12]
Bonjour,

Je me demandais s'il existait un maven repository pour le projet, car il n'y a aucune mention de celui-ci ?
Et s'il n'existait pas, s'il serait possible de l'ajouter ?

Je vous remercie d'avance pour la réponse.

**Comment by mica-alex** [comment]
+1 having this plugin on a Maven repository would be hugely helpful

**Comment by Litarvan** [comment]
Hello! Déso l'issue s'est perdue dans mes notifs GitHub, le dépôt existe déjà depuis longtemps:
```groovy
repositories {
    maven {
        url 'https://litarvan.github.io/maven'
    }
}

dependencies {
    compile 'fr.litarvan:openauth:1.1.1'
}
```
Le lien du dépôt est une 404 c'est normal il n'y a pas de page d'index mais il marche :)
