### ISSUE TITLE
OPENAUTH_AUTH_POINTS

### ISSUE THREAD

**Issue by Anko38** [Litarvan/OpenAuth#2]
Hey Litarvan.
Je suis en train de faire mon serveur d'authentification avec openauth et openauth-server.
mais j'ai un problème côté client, je peux pas définir AuthPoints. OPENAUTH_AUTH_POINTS, il n'est pas reconnu.

Quand je met NORMAL_AUTH_POINTS :
![capture](https://user-images.githubusercontent.com/19715481/28227112-df7895c4-68d8-11e7-83a3-8a9f078d8b26.PNG)

Merci ;)

PS: Pour l'inscription je demande que le Mdp et le pseudo ? car dans la bdd il y ait plein d'autres colonnes dont je ne comprends pas trop l'existence

**Comment by Litarvan** [comment]
Tu ne demandes que le MDP et le Pseudo les autres colonnes sont gérées automatiquement. Il ne faut pas mettre OPENAUTH_AUTH_POINTS mais bien laisser les NORMAL_AUTH_POINTS, et ton erreur c'est car tu as mis en HTTPS alors que ton site ne le supporte pas (et pour preuve teste d'aller en https sur auth.hexi.fr avec ton navigateur il te dira qu'il y a un problème).

**Comment by Anko38** [comment]
Ok, merci ;)
