### ISSUE TITLE
[FEATURE] Rollback/correct some #18 things related to javafx

### ISSUE THREAD

**Issue by FlowArg** [Litarvan/OpenAuth#25]
The #18 and #22 PRs introduce new features, improvements, deprecation-marks, and I'm glad to hear that this lib receives some new contributions.
But the [`Added openJFX as dependency so users are not forced into downloading the JFX JDK.`](https://github.com/Litarvan/OpenAuth/pull/18/commits/02c43396b7afec00e50d0f1964bbdc6756b410db) thing is a mess and has to be removed as soon as possible. Why? Because it automatically ADDS NEW DEPENDENCIES to the user project that isn't useful for the most of people.
Because there are many people who are still in Java 8 or with some others Java versions like 18 or 17 (Because Java 11 isn't very useful ATM) or they just don't use at all JavaFx. It's a really bad idea to add these dependencies that are useful ONLY if the user needs JavaFx and uses a Java 11 distribution without JavaFx.

Furthermore, we receive this week a lot of help requests because this update broke a lot of launcher because JavaFX clashes. Yay...
Now, we have to include the library and exclude ALL JavaFx dependencies... Pretty cool
```gradle
implementation ('fr.litarvan:openauth:1.1.3') {
    exclude module: 'javafx-media'
    exclude module: 'javafx-controls'
    exclude module: 'javafx-swing'
    exclude module: 'javafx-base'
    exclude module: 'javafx-graphics'
    exclude module: 'javafx-web'
}
```

I think an authentication library doesn't have to include graphics dependencies that also takes a lot of space on the disk.

NOTE:
I saw also a CI that maybe need JavaFx to functions.
1) Is the CI useful for this lib? Does this lib contains some unit tests ?
2) Can the CI setups itself a valid jdk with JavaFx ?

Thanks you for reading

**Comment by Litarvan** [comment]
Yeah I thought of that, should have waited before releasing. It either works for Java >8 or <=8 🤡 state of Java and JavaFX is clownesque but well, retro compat is better so I reverted those changes in 1.1.4.

(And CI is just to check that this is building correctly, nothing fancy)
