### ISSUE TITLE
The method specified in the request is not allowed for the resource identified by the request URI

### ISSUE THREAD

**Issue by MarcoAbricot** [Litarvan/OpenAuth#3]
Hey, j'ai un problème avec OpenAuth (on ne dirait pas que c'est le serveur, soit c'est le serveur et je suis con ou sinon j'ai raison) je n'arrive pas à me connecter au serveur, ça m'affiche ça. 

![image](https://user-images.githubusercontent.com/37117103/48311314-3c0eda80-e59e-11e8-9877-c0a079b26b85.png)

Merci. :)

**Comment by Litarvan** [comment]
Tu es sur le serveur de Mojang officiel ? Je peux voir ton initialisation d'objet Authenticator ? `Authenticator authenticator = new Authenticator(...);`

**Comment by MarcoAbricot** [comment]
Exactement comme c'est expliqué sur la page GitHub ^^ `		AuthPoints points = new AuthPoints("http://celestio.zeternia.fr/launcher/oauth/app/authenticate.php", "http://celestio.zeternia.fr/launcher/oauth/app/refresh.php", "http://celestio.zeternia.fr/launcher/oauth/app/validate.php", "http://celestio.zeternia.fr/launcher/oauth/app/logout.php", "http://celestio.zeternia.fr/launcher/oauth/app/invalidate.php");
		Authenticator authenticator = new Authenticator("http://celestio.zeternia.fr/launcher/oauth/", points);`

**Comment by Litarvan** [comment]
Remplace par : `Authenticator authenticator = new Authenticator("http://celestio.zeternia.fr/launcher/oauth/", AuthPoints.NORMAL_AUTH_POINTS);`

**Comment by MarcoAbricot** [comment]
Yep, c'est bon. Je me disais bien que c'était un problème par rapport à moi ^^' merci :D

**Comment by MarcoAbricot** [comment]
Zw
